export default {
    notification_title: "Information",
    no_notification: "Aucune notification",
    forgot_password_link: "Mot de passe oublié",
    my_rides: "Mes réservations",
    notification: "Notifications",
    location_error: 'Impossible de déterminer votre position. Vérifiez que la localisation est activée et autorisée pour Heeroo.',
    email_placeholder: "E-mail",
    Error: "Erreur",
    password_placeholder: "Mot de passe",
    login_button: "Se connecter",
    register_link: "S'inscrire",
    forgot_password_link1: "Mot de passe oublié?",
    forgot_password_link2: "Réinitialiser",
    forgot_password_confirm: "Êtes-vous sûr de vouloir réinitialiser votre mot de passe?",
    facebook_login_button: 'Se connecter avec Facebook.',
    password_blank_messege: 'Ce champ ne peut pas rester vide.',
    password_alphaNumeric_check: 'Le mot de passe doit être composé d\'au moins 1 caractère alphanumérique et d\'une longueur de 8 à 15 caractères.',
    password_complexity_check: 'Le mot de passe doit comporter au moins 1 minuscule, 1 majuscule, 1 chiffre, 1 caractère spécial et une longueur de 6 à 10 caractères.',
    valid_email_check: 'Merci de renseigner un e-mail valide.',
    email_not_found: 'Votre e-mail n\'a pas été trouvé dans la base de données',
    valid_rider: "Merci de vous connecter avec un compte chauffeur valide",
    email_already_used: 'Un autre compte utilise deja cette e-mail',
    facebook_login_error: 'Erreur de connexion. ',
    apple_signin_error: "L'inscription Apple n'est pas configuré dans developer.appple.com ou vous avez déjà utilisé le même e-mail pour vous inscrire.",
    forgot_password_success_messege: 'Un lien de réinitialisation de votre mot de passe a été envoyé sur votre boîte e-mail, veuillez vérifier et réinitialiser votre nouveau mot de passe.',
    facebook_login_auth_error: 'Erreur de connexion avec Facebook Connect :',
    static_notification_title: 'Notification',
    modal_closed: 'Le mode a été fermé.',
    refferal_code_validation_modal: 'Validation de votre code de parrainage...',
    refferal_id_not_match_error: 'Votre code de parrainage est erroné.',
    registration_title: 'Inscription',
    first_name_placeholder: 'Prénom',
    first_name_blank_error: "Merci de renseigner votre prénom",
    last_name_placeholder: 'Nom',
    last_name_blank_error: 'Merci de renseigner votre nom',
    login_title: 'Se connecter via Mobile',
    mobile_no_placeholder: 'Téléphone Mobile',
    mobile_no_blank_error: 'Merci de renseigner un numéro de téléphone mobile.',
    otp_error: 'Merci d\'entrer le code de vérification',
    otp_here: 'Merci d\'entrer le code de vérification ici',
    sending_otp: "Envoyer le code...",
    authorize: 'Autoriser',
    request_otp: "Demander un code",
    firebase_otp_error: 'Erreur d\'authentification. Vérifiez votre numéro de mobile. Vous devez ajouter un indicatif.',
    spacer_message: 'OU CONNECTEZ-VOUS AVEC',
    confrim_password_placeholder: 'Confirmez le mot de passe',
    confrim_password_not_match_err: 'Le mot de passe doit être identique',
    referral_id_placeholder: 'Code chauffeur (Optionnel)',
    register_button: 'Inscrivez-vous maintenant',
    email_exist_error: 'L\'adresse e-mail est déjà utilisée par un autre compte.',
    Account_linking_error: 'Erreur de liaison de compte',
    send_email_button: 'Envoyer un E-mail',
    book_your_ride_menu: 'Nouvelle réservation',
    profile_setting_menu: 'Profil',
    my_wallet_menu: 'Mon portefeuille',
    my_rides_menu: 'Mes réservations',
    about_us_menu: 'A propos',
    logout: 'Déconnexion',
    photo_upload_action_sheet_title: 'Choisissez un type de media?',
    camera: 'Caméra',
    galery: 'Galerie Photo',
    cancel: 'Annuler',
    yes: 'Oui',
    network_request_failed: 'Échec de connexion au réseau',
    password_update_messege: 'Votre mot de passe a été mis à jour avec succès',
    delete_account_modal_title: 'Confirmation',
    delete_account_modal_subtitle: 'Voulez-vous supprimer votre compte ?',
    profile_page_title: 'Mon Profil',
    my_wallet_title: 'Ma Balance',
    profile_page_subtitle: 'Détail de profil',
    location_lebel: 'Localisation',
    language_lebel: 'Langue',
    preffer_language: 'Anglais',
    change_password_lebel: 'Changer le mot de passe',
    delete_account_lebel: 'Supprimer le compte',
    change_password_modal_title: 'Changer le mot de passe?',
    old_password_placeholder: 'Ancien mot de passe',
    new_password_placeholder: 'Nouveau mot de passe',
    old_password_validation_error: 'Entrer l\'ancien mot de passe',
    new_password_validation_error: 'Entrer le nouveau mot de passe',
    update_button: 'Mettre à jour',
    update_profile_title: 'Mettre à jour votre profil',
    map_screen_where_input_text: 'Saisissez l’adresse de départ ',
    map_screen_drop_input_text: 'Saisissez l’adresse d’arrivée',
    driver_finding_alert: 'Nous recherchons le chauffeur le plus proche',
    no_driver_found_alert_title: 'Alerte!',
    no_driver_found_alert_messege: 'Désolé, aucun chauffeur disponible pour le moment. Veuillez réessayer plus tard',
    no_driver_found_alert_OK_button: 'Annuler',
    no_driver_found_alert_TRY_AGAIN_button: 'Réessayer',
    pickup_and_drop_location_blank_error: 'Entrer l\'adresse de départ et d\'arrivée',
    pickup_location_blank_error: 'Entrer l\'adresse de départ',
    drop_location_blank_error: 'Entrer l\'adresse d\'arrivée',
    car_type_blank_error: 'Sélectionner le type de véhicule',
    choose_vehicle: 'Choisissez votre véhicule',
    congratulation: 'Félicitations!',
    refferal_bonus_messege_text: 'Montant de votre bonus de parrainage -',
    map_screen_title: 'Trouver un chauffeur',
    cab_selection_title: 'Choisissez votre chauffeur',
    cab_selection_subtitle: 'Cliquez sur le type de véhicule souhaité et réservez le maintenant',
    not_available: 'Non disponible',
    book_now_button: 'Réserver maintenant',
    contact_details: 'Détail de contact',
    phone: 'Téléphone',
    my_wallet_tile: 'Mon portefeuille',
    wallet_ballance: 'Votre relevé',
    add_money: 'Ajouter de l\'argent',
    transaction_history_title: 'Historique des transactions',
    successfully: 'Confirmé',
    form_wallet: 'formulaire du portefeuille',
    Transaction_Id: 'Id de la Transaction  ',
    ride_list_title: 'Mes réservations',
    no_car_assign_text: 'Aucun voiture n\'a été assignée',
    not_found_text: 'Non trouvé',
    ride_details_page_title: 'Mes détails de réservation',
    you_rated_text: 'Votre notation',
    car_no_not_found: 'Numéro de voiture non trouvé',
    track_now_button: 'Suivre maintenant',
    bill_details_title: 'Détails de facturation',
    your_trip: 'Votre course',
    discount: 'Remise',
    promo_apply: '(Promotion appliquée)',
    grand_total: 'Grand Total',
    payment_status: 'Statut du paiement',
    paynow_button: 'Payer maintenant',
    call_driver: 'Appel chauffeur',
    booked_cab_title: 'Chauffeur réservé',
    you_selected: 'Votre sélection -',
    otp: 'CODE :',
    driver_assign_messege: 'Un chauffeur sera assigné très prochainement..',
    cancel_ride: 'Annuler la course',
    rider_cancel_text: 'Annuler la course',
    submit_rating: 'SOUMETTRE LA NOTATION',
    cancel_messege1: 'Votre course incluant votre numéro de réservation',
    cancel_messege2: 'a été annulée avec succès',
    dont_cancel_text: 'Ne pas annuler',
    cancel_reason_modal_title: 'Quelle est la raison de l\'annulation',
    chat_title: 'Chat',
    send_button_text: 'Envoyer',
    chat_input_title: 'Ecrivez quelque chose d\'agréable...',
    chat_not_found: 'Pas de discussion trouvée',
    card_payment_blank_error: 'Veuillez remplir tous les détails correctement.',
    payment_amound_error: 'Le montant du paiement est trop faible.',
    invalid_card_details_error: 'Carte bancaire non valide.',
    success_payment: 'Transaction accceptée',
    confrimation: 'Confirmation',
    payment_alert: 'Voulez-vous supprimer votre carte ?',
    please_wait: 'Merci de patienter...',
    enterCVV: 'Merci d\'entrer votre numéro CVV',
    your_promo: 'Votre promotion',
    promo_exp: 'Désolé, le code promo et la date limite d\'utilisation est dépassée.',
    promo_limit: 'Désolé, la date limite d\'utilisation est dépassée.',
    promo_eligiblity: 'DÉSOLÉ!\nvous n\'êtes pas autorisé à utiliser ce code promo.',
    payment: 'Paiement',
    payment_by_card: 'Carte bancaire',
    choose_payment: 'Moyen de paiement',
    payment_to_choose: 'À choisir',
    choose_payment_prompt: 'Choisissez espèces ou carte avant de confirmer la course.',
    bill_details: 'Détails de facturation',
    apply_promo: 'Appliquer le code promo',
    apply: "APPLIQUER",
    driver_near: "Le chauffeur arrive au point de départ",
    your_fare: 'Prix',
    promo_discount: 'Remise promotionnelle',
    wallet_discount: 'Remise de portefeuille',
    payable_ammount: 'Montant dû',
    use_wallet_balance: 'Utilisez votre argent disponible sur votre portefeuille (Vous disposez de ',
    pay_cash: 'Payer en espèces',
    pay_card: 'Payer par carte bancaire',
    proceed_pay: 'Procéder au paiement',
    save_card: 'Vos cartes sauvegardées',
    thanks: 'Merci de votre notation',
    skip: 'Passer',
    receipt: 'Reçu',
    rate_ride: 'MERCI DE NOTER LA COURSE',
    err: 'Erreur!',
    route_not_found: 'Impossible de trouver un itinéraire',
    sorry: 'Désolé',
    multipleBooking: 'L\'application ne permet pas d\'effectuer plusieurs réservations.',
    driver_not_found: 'Nous ne pouvons pas trouver de chauffeur pour le moment. contacter l\'administrateur !!',
    new_booking_request_push_notification: 'Vous avez une nouvelle demande de réservation',
    fare_details: 'Détail du prix',
    base_fare: 'Prix de base',
    convenience_free: 'Commission',
    total_fare: 'Total',
    inclusive_tax: '(TVA inclus)',
    nb: 'N.B.: Le prix de la course sera augmenté s\'il y a des péages sur le trajet, si la destination change ou si le trajet a pris plus de temps en raison de la circulation',
    confrim_booking: 'Confirmer',
    estimate_fare_text: 'Prix approximatif de la course',
    done: 'Terminer',
    notification_headerText: 'Notification',
    notification_not_found: 'Aucun notification trouvée',
    track_cab: 'Suivre le chauffeur',
    location_permission: 'Lieu autorisé',
    ask_me_later: 'Me demander plus tard',
    min_order_value: 'Montant minimum d\'une course-',
    add_money_tile: 'Ajouter de l\'argent',
    addMoneyTextInputPlaceholder: 'Choisir un montant',
    transactionFaildMsg: 'Transaction refusée',
    payWithCard: 'Payer par carte',
    CardPaymentAmount: 'Payer par CB',
    CashPaymentAmount: 'Payer en espèces',
    WalletPayment: 'Payer avec le portefeuille',
    pay_mode: 'Mode de paiement',
    Balance: 'Relevé',
    android_channel: 'Notifications',
    write_message: 'Ecrire votre message',
    terms: "Conditions générales de vente",
    panic_text: "Appel SOS",
    panic_question: "Voulez-vous vraiment effectuer un appel d'urgence?",
    email_login: 'Connexion par E-mail',
    register_email: 'Inscription par E-mail',
    ok: 'OK',
    //
    where_do_want_go: "WHERE DO YOU WANT TO GO?",
    where_do_want_goFR: "Où allez-vous ?",
    select: "Selectionner",
    from_position: "Départ",
    to_position: "Arrivée",
    Detailsdelacourse: "Details de la course",
    Commissionprovisoire: "Prix de la course",
    Annulerlacourse: "Annuler la course",
    voiture_model_numero: "Voiture",
    driver_book_text: "Coursier",
    hello: "Bonjour",
    go_register_link1: "Vous n’avez pas de  compte?",
    go_register_link2: "Inscrivez-vous",
    go_login_link1: "Vous avez déjà un compte?",
    go_login_link2: "Connectez-vous",
    go_email_link: "Email",
    no_reservation: "Aucune réservation",
    paymentCash: "Espèces",
    email_uncorrect: "Le e-mail que vous avez saisi est incorrect.",
    login_too_many: "Trop de tentatives : la connexion à ce compte est bloquée quelques minutes par sécurité. Réessayez plus tard, ou réinitialisez votre mot de passe.",
    login_network: "Connexion au serveur impossible. Vérifiez votre connexion internet et réessayez.",
    login_disabled: "Ce compte a été désactivé. Contactez le support.",
    login_failed: "Connexion impossible :",
    password_uncorrect: "Le mot de passe que vous avez saisi est incorrect.\nVeuillez ressaisir le mot de passe ou le réinitialiser. ",
    alert_title: "Information",
    driver_near_you: "Le chauffeur arrive dans quelque instant à l’adresse de départ de la course. ",
    rider_cancel_course_title: "Alerte",
    rider_cancel_course: "Le passager a annulé la course",
    message_notification_title: "Message",
    rate_notification_title: "Notation de la course",
    rate_notification_body: "vous a attribué la note de ",
    emailExistInPhoneAccountTitle: "Erreur",
    emailExistInPhoneAccount: "Merci d'utiliser la connexion via N° de téléphone, utilisée lors de l'inscription",
    resetEmailExistInPhoneAccount: "Cet email est utilisé pour un compte inscrit via N° de téléphone. Vous ne pouvez pas réinitialiser votre mot de passe"
}
