export default {
    error: "Erreur",
    alert: "Information",
    payment: "Paiement",
    valid_identityfront_check: "Ce document est obligatoire",
    // Crédit chauffeur (recharge Wave)
    credit_balance: 'Mon crédit',
    topup_button: 'Recharger',
    topup_title: 'Recharger mon crédit',
    credit_insufficient_title: 'Crédit insuffisant',
    credit_insufficient_msg: 'Votre crédit est de {balance} FCFA. Il faut au moins {min} FCFA pour accepter une course : rechargez-le depuis « Mes revenus ».',
    topup_hint: 'Choisissez un montant, puis payez avec Wave. La commission de chaque course est prélevée sur ce crédit.',
    topup_amount_placeholder: 'Autre montant (FCFA)',
    topup_confirm: 'Payer avec Wave',
    topup_min_error: 'Le montant minimum est de 1 000 FCFA.',
    topup_pending: 'Paiement Wave en attente de confirmation…',
    topup_success: 'Votre crédit a été rechargé.',
    topup_failed: "Le paiement n'a pas abouti. Aucun montant n'a été débité.",
    driver_near_you: "Le chauffeur arrive dans quelque instant à l’adresse de départ de la course. ",
    about_us: 'A propos',
    Error: "Erreur",
    contact_details: 'Contact',
    estimatedIncome: 'Revenu estimé : ',
    email: 'E-mail',
    phone: 'Téléphone',
    login_page_title: 'CONNEXION CHAUFFEUR',
    driver_account_approve_err: 'Votre compte n\'est pas encore approuvé en tant que chauffeur.',
    account_not_exsist: 'Votre compte chauffeur n\'existe pas.',
    driver_ride_complete_status: 'Le chauffeur a terminé votre course. Votre numéro de réservation est',
    please_wait: 'Calcul du tarif de la course',
    on_trip: 'En course',
    verify_informations: 'Veuillez verifier vos informations',
    complete_trip: 'COURSE TERMINÉE',
    account_successful_done: 'Votre compte a été créé avec succès et est en attente de validation de l\'administrateur.',
    image_size_error: 'La taille de l\'image ne doit pas dépasser 2 Mo.',
    password_blank_error: 'Le champ mot de passe ne peut pas rester vide.',
    password_complexity_alphabet: 'Le mot de passe doit être composé d\'au moins 1 caractère alphanumérique et d\'une longueur de 8 à 15 caractères.',
    password_complexity_complex: 'Le mot de passe doit comporter au moins 1 minuscule, 1 majuscule, 1 chiffre, 1 caractère spécial et une longueur de 6 à 10 caractères.',
    driver_registration: 'Inscription Chauffeur',
    first_name: 'Prénom',
    first_name_error: 'Merci de renseigner votre prénom',
    last_name: 'Nom',
    last_name_error: 'Merci de renseigner votre nom',
    email_blank_error: 'Merci d\'entrer un e-mail valide',
    mobile: 'Numéro de téléphone mobile',
    password: 'Mot de passe',
    confrim_password: 'Confirmer mot de passe',
    password_not_match: 'Le mot de passe doit être identique',
    vehicle_model_name: 'Catégorie de véhicule',
    vehicle_model_name_blank_error: 'La marque du véhicule doit être renseignée',
    vehicle_reg_no: 'N° Immatriculation',
    vehicle_number_blank_err: 'Le N° Immatriculation doit être renseigné',
    upload_driving_lisence: 'Téléchargez votre attestation de chauffeur',
    image_size_warning: '(Taille d\'image: 2 Mo Max)',
    reg_no: 'S\'inscrire maintenant',
    update_profile: 'Mettre à jour votre profil',
    valid_mobile_number: 'Merci de renseigner un numéro de téléphone valide',
    update_now: 'Mettre à jour',
    no_notification: 'Aucun notification trouvée',
    forgot_password_link1: "Mot de passe oublié ?",
    forgot_password_link2: "Réinitialiser",
    valid_email_err: 'Merci d\'entrer un E-mail valide',
    send_email: 'Envoyer un E-mail',
    enter_code: 'Entrer le code',
    submit: 'Soumettre',
    change_password: 'Changer le mot de passe?',
    old_password: 'Ancien mot de passe',
    old_password_err: 'Merci d\'entrer l\'ancien mot de passe',
    new_password: 'Nouveau mot de passe',
    new_password_err: 'Merci d\'entrer le nouveau mot de passe',
    update: 'Mettre à jour',
    login: 'Connexion',
    booking_request: 'Demande de réservation',
    profile_settings: 'Paramètre de profil',
    incomeText: "Mes gains",
    my_bookings: 'Mes réservations',
    sign_out: 'Déconnexion',
    rider_ride_cancel_text: 'Le passager a annulé la course',
    mobile_no_found: 'Numéro de mobile non trouvé',
    firebase_otp_error: 'Erreur d\'authentification. Vérifiez votre numéro de mobile. Vous devez ajouter un indicatif.',
    login_title: 'Connexion Chauffeur',
    mobile_no_placeholder: 'Téléphone Mobile',
    mobile_no_blank_error: 'Merci de renseigner un numéro de téléphone mobile.',
    otp_error: 'Merci d\'entrer le code de vérification',
    otp_here: 'Merci d\'entrer le code de vérification ici',
    sending_otp: "Envoyer le code...",
    authorize: 'Autoriser',
    request_otp: "Demander un code",
    driver_journey_err: 'Le chauffeur a commencé la course. Votre numéro de réservation est',
    wait_for_rider: 'EN APPROCHE',
    rider_notified: 'Le passager sera informé de votre présence automatiquement',
    start_trip: 'DÉMARRER LA COURSE',
    cancel_reson_1: 'Impossible de contacter le chauffeur',
    cancel_reson_2: 'Le véhicule ne se déplace pas dans ma direction',
    cancel_reson_3: 'Autre raison',
    cancel_reson_4: 'Chauffeur refusé',
    cancel_reson_5: 'Le véhicule n\'est pas arrivé à l\'heure prévue',
    api_error: 'Erreur Google places API',
    accept_booking_request: 'Un chauffeur vient d’accepter la course',
    pickup_location: 'Adresse de départ',
    drop_location: 'Adresse d\'arrivée',
    ignore_text: 'Ignorer',
    modal_close: 'Le mode a été fermé.',
    alert_text: 'Alerte',
    ignore_job_title: 'Souhaitez-vous refuser cette demande?',
    cancel: 'Annuler',
    ok: 'OK',
    accept: 'Accepter',
    task_list: 'Réservations en cours',
    rider_not_here: 'Aucune demande de réservation',
    booking_request_rejected: 'Votre demande de réservation a été rejetée par les chauffeurs adressés.',
    driver_requested_for_payment: 'Le chauffeur est en attente du règlement. Le numéro de réservation est',
    request_payment: 'Demande de règlement',
    my_rides: 'Mes réservations',
    password_reset_link: 'Un lien de réinitialisation de mot de passe a été envoyé sur votre boîte mail, veuillez vérifier et réinitialiser votre nouveau mot de passe.',
    notification: 'Notifications',
    chat_blank: 'Merci de rédiger votre message...',
    send_msg: ' Vous envoyez un message: \n',
    driver: 'Chauffeur',
    chat_history_not_found: 'Pas de discussion trouvée',
    chat: 'Chat',
    send: 'Envoyer',
    type_messege: 'Écrire votre message',
    photo_upload_action_sheet_title: 'Choisissez un type de media?',
    camera: 'Caméra',
    galery: 'Galerie Photo',
    yes: 'Oui',
    no: 'Non',
    notYetPaid: 'Pas encore',
    password_change: 'Votre mot de passe a été mis à jour avec succès',
    confrim: 'Confirmation',
    delete_account_question: 'Voulez-vous supprimer votre compte?',
    my_profile: 'Mon Profil',
    active_status: 'Statut Activé',
    profile_details: 'Détails de profil',
    location: 'Localisation',
    mobile_no: 'Téléphone Mobile',
    preffered_lang: 'Langue préférée',
    lang: 'Anglais',
    delete_account: 'Supprimer le compte',
    payment_info: 'Information de règlement du passager',
    booking_details: 'Détail de réservation',
    you_rate_text: 'Vous avez été noté',
    no_rated_text: 'Vous n\'avez pas de note',
    bill_details: 'Détails de facturation',
    your_trip: 'Votre course',
    total_bill: 'Total',
    include_tax: 'TVA inclus',
    total_payable: 'Commision',
    go_to_booking: 'Voir la course',
    my_booking: 'Mes réservations',
    job_ignore: 'Voulez-vous refuser cette demande de réservation?',
    show_modal: 'Voir les modalités',
    notification_title: 'Information',
    register: 'Inscription',
    today: 'Gains du jour',
    thismonth: 'Gains du mois',
    totalearning: 'Gains Total',
    convenienceFee: 'Commission',
    paymentStatus: 'Statut du règlement',
    payment_mode: 'Mode de paiement',
    customer_payable: 'A la charge du passager',
    discount_amount: 'Montant de la remise',
    CardPaymentAmount: 'Paiement par CB -',
    CashPaymentAmount: 'Paiement en espèces -',
    WalletPayment: 'Payer avec le portefeuille -',
    android_channel: 'Notifications',
    terms: "Conditions générales de vente",
    email_login: 'Connexion par E-mail',
    register_email: 'Inscription par E-mail',
    ok: 'OK',
    spacer_message: 'OU CONNECTEZ-VOUS AVEC',
    password_blank_messege: 'Ce champ ne peut pas rester vide.',
    confrim_password_placeholder: 'Confirmer le mot de passe',
    confrim_password_not_match_err: 'Le mot de passe doit être identique',
    valid_email_check: 'Merci de renseigner un e-mail valide.',
    forgot_password_link: "Mot de passe oublié?",
    forgot_password_confirm: "Êtes-vous sûr de vouloir réinitialiser votre mot de passe?",
    forgot_password_success_messege: 'Un lien de réinitialisation de votre mot de passe a été envoyé sur votre boîte e-mail, veuillez vérifier et réinitialiser votre nouveau mot de passe.',
    email_not_found: 'E-mail non trouvé dans la base de données',
    email_already_used: 'Un autre compte utilise deja cette e-mail',
    password_alphaNumeric_check: 'Le mot de passe doit être composé d\'au moins 1 caractère alphanumérique et d\'une longueur de 8 à 15 caractères.',
    password_complexity_check: 'Le mot de passe doit comporter au moins 1 minuscule, 1 majuscule, 1 chiffre, 1 caractère spécial et une longueur de 6 à 10 caractères.',
    email_placeholder: "E-mail",
    password_placeholder: "Mot de passe",
    login_button: "Se connecter",
    register_link: "S'inscrire",
    //
    hello: "Bonjour",
    from_position: "Départ",
    to_position: "Arrivée",
    get_direction: "Itinéraire",
    go_register_link1: "Vous n’avez pas de compte ?",
    go_register_link2: "Inscrivez-vous",
    go_login_link1: "Vous avez déjà un compte ?",
    go_login_link2: "Connectez-vous",
    montantNet: "Montant net de frais : ",
    go_email_link: "Email",
    no_reservation: "Aucun réservation",
    yourinthepositiontitle: "Position check",
    yourintheposition: "You are in the same area as the rider ",
    directionsdialogTitle: "Lancer l’itiniéraire",
    directionsdialogMessage: "Merci de choisir l’application",
    directionscancelText: "Annuler",
    email_uncorrect: "Le email que vous avez saisi est incorrect.",
    password_uncorrect: "Le mot de passe que vous avez saisi est incorrect.\nVeuillez ressaisir le mot de passe ou le réinitialiser. ",
    trip_in_progress: "Course en cours",
    is_client_pay: "Le client a-t-il payé ?",
    clientPayedEndRide: "Le client vous a-t-il payé la course en espèces ?",
    endRide: "Oui, terminer la course",
    message_notification_title: "Message",
    companyName: "Nom de votre société",
    companyName_no_blank_error: "Merci de renseigner le nom de votre société.",
    companyAddress: "Adresse de votre société",
    companyAddress_no_blank_error: "Merci de renseigner l'adresse de votre société.",
    ticket_title: "Billet collectif",
    ticket_rules: "TRANSPORT PUBLIC ROUTIER COLLECTIF DE PERSONNES \n\nBILLET COLLECTIF\n(Arrêté du 14 Février 1986 - Article 5)\net\nORDRE DE MISSION\n(Arrêté du 6 Janvier 1993 - Article 3)",
    ticket_start_address: "Location de véhicule avec chauffeur",
    ticket_driver: "Conducteur",
    ticket_rider: "Passager",
    ticket_ride_date: "Commande",
    ticket_ride_deal_date: "Prise en charge",
    ticket_ride_start_address: "Lieu prise en charge",
    ticket_ride_end_address: "Destination",
    ticket_cost: "Tarif",
    ticket_via: "Via",
    file_identity_front: "Pièce d’identité recto",
    file_identity_back: "Pièce d’identité verso",
    carteGrise: "Carte grise",
    permis: "Permis de conduire",
    carteVTC: "Carte VTC",
    rir: "Relevé d'information restreint (RIR)",
    attestation: "Attestation à titre onéreux",
    carteVerte: "Carte verte",
    assuranceRC: "Assurance Responsabilité Civile",
    photoAvantVehicule: "Photo avant du véhicule",
    photoChauffeur: "Photo du chauffeur",
    emailExistInPhoneAccountTitle: "Erreur",
    emailExistInPhoneAccount: "Merci d'utiliser la connexion via N° de téléphone, utilisée lors de l'inscription",
    resetEmailExistInPhoneAccount: "Cet email est utilisé pour un compte inscrit via N° de téléphone. Vous ne pouvez pas réinitialiser votre mot de passe"
}