export default {
    isoCountryCode: "isoCountryCode",
    booking_date: 'Date de réservation',
    trip_start_time: 'Heure de début de la course',
    trip_end_time: 'Heure de fin de la course',
    customer_name: 'Client',
    car_type: 'Catégorie de véhicule',
    vehicle_no: 'N° Immatriculation',
    pickup_address: 'Adresse de départ',
    drop_address: 'Adresse d\'arrivée',
    assign_driver: 'Chauffeur assigné',
    booking_status: 'Statut de la réservation',
    trip_cost: 'Prix',
    discount_ammount: 'Remise',
    payment_status: 'Statut du paiement',
    payment_mode: 'Mode de paiement',
    booking_text: 'Réservations',
    image: 'Image',
    name: 'Nom',
    rate_per_km: 'Prix au kilomètre',
    rate_per_hour: 'Prix à l\'heure',
    min_fare: 'Prix de base',
    convenience_fee: 'Commission en CFA',
    convenience_fee_percent: 'Commission en %',
    today_text: "Aujourd'hui",
    gross_earning: 'Marge',
    admin_convenience_fee: 'Gain Commission',
    this_month_text: 'Mois',
    total: 'Total',
    real_time_driver_section_text: 'Chauffeurs connectés',
    allow_location: 'Autorisé le lieu',
    sign_in: 'S\'inscrire',
    email_address: 'E-mail',
    password: 'Mot de passe',
    sign_in_error: 'Erreur d\'inscription. Merci de vérifier votre e-mail et votre mot de passe.',
    device_type: 'Type de support',
    user_type: 'Type d\'utilisateur',
    title: 'Titre',
    body: 'Corp',
    push_notification_title: 'Push Notifications',
    promo_name: 'Nom de la promotion',
    description: 'Description',
    promo_type: 'Type de promotion',
    promo_discount_value: 'Valeur de la remise',
    max_limit: 'Montant maximum de la remise',
    min_limit: 'Nombre minimum de commandes',
    start_date: 'Date de démarrage (jj/mm/aaaa)',
    end_date: 'Date de fin (jj/mm/aaaa)',
    promo_usage: 'Limite d\'usage de la promo',
    promo_used_by: 'Promo utilisée par',
    promo_offer: 'Offres et promotions',
    refferal_bonus: 'Bonus de parrainage',
    submit: 'Soumettre',
    update_failed: 'Mise à jour échouée',
    first_name: 'Prénom',
    last_name: 'Nom',
    email: 'E-mail',
    mobile: 'Mobile',
    profile_image: 'Image de profil',
    vehicle_model: 'Modèle de véhicule',
    account_approve: 'Compte approuvé',
    driver_active: 'Statut chauffeur actif',
    lisence_image: 'Image de la license',
    vehicle_number: 'N° Immatriculation',
    wallet_balance: 'Relevé',
    signup_via_refferal: 'S\'inscrire avec un code parrainage',
    refferal_id: 'Id parrainage',
    all_user: 'Tous les utilisateurs',
    notification_sent: ' notifications envoyées.',
    notification_sent_failed: 'L\'envoi de Notification a échoué.',
    no_user_match: 'Aucun utilisateur correspondant',
    no_user_matching: 'Aucun utilisateur trouvé correspondant à votre sélection.',
    dashboard_text: 'Tableau de bord',
    user: 'Utilisateurs',
    booking_history: 'Réservations',
    promo: 'Promos',
    logout: 'Déconnexion',
    driver_earning: 'Historique des gains chauffeur',
    earning_amount: 'Montant des gains',
    driver_name: 'Nom chauffeur',
    driver_image: 'Image chauffeur',
    months: 'Mois',
    year: 'Années',
    vehicle_type: 'N° Immatriculation',
    lisence_no: 'N° License',
    booking_discount_earning: 'Remise',
    trip_cost_driver_share: 'Prix de la course/Montant partagé avec chauffeur',
    Gross_trip_cost: "Marge",
    Discounts: "Remises",
    Customer_paid: "Client payé",
    Profit: "Bénéfices ( Client payé - Coût de la course )",
    earning_reports: 'Rapport des gains',
    cash_payment_amount: 'Montant des paiements Espèces',
    card_payment_amount: 'Montant des paiements CB',
    wallet_payment_amount: 'Montant des paiements via portefeuille',
    payment_getway: 'Passerel de paiement',
    currency_symbol: 'Symbole Devise',
    currency_code: 'Code Devise',
    settings_title: 'Paramètres',
    settings_label1: 'Espèces',
    settings_label2: 'Portefeuille',
    settings_label3: 'Braintree',
    settings_label4: 'Stripe',
    payment_modes_title: 'Mode de paiement',
    queue: 'Occupé',
    createdAt: 'Date de création',
    panic_title: 'Paramètres SOS',
    panic_num: 'Numéro du SOS',
    companyName: "Nom de votre société",
    companyAddress: "Adresse de votre société",
    identity: "Pièce d’identité",
    country: "Pays",

}